# Generated by Django 4.2.9 on 2024-05-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusers',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyusers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1),
        ),
    ]
